# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{henshin}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["hawx"]
  s.date = %q{2010-05-19}
  s.default_executable = %q{henshin}
  s.description = %q{Henshin is a static site generator, with a plugin system and more}
  s.email = %q{m@hawx.me}
  s.executables = ["henshin"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".yardoc/checksums",
     ".yardoc/objects/Hash.dat",
     ".yardoc/objects/Hash/to_options_i.dat",
     ".yardoc/objects/Henshin.dat",
     ".yardoc/objects/Henshin/CSSGenerator.dat",
     ".yardoc/objects/Henshin/CSSGenerator/generate_i.dat",
     ".yardoc/objects/Henshin/Defaults.dat",
     ".yardoc/objects/Henshin/Gen.dat",
     ".yardoc/objects/Henshin/Gen/config_3D_i.dat",
     ".yardoc/objects/Henshin/Gen/config_i.dat",
     ".yardoc/objects/Henshin/Gen/content_3D_i.dat",
     ".yardoc/objects/Henshin/Gen/content_i.dat",
     ".yardoc/objects/Henshin/Gen/date_3D_i.dat",
     ".yardoc/objects/Henshin/Gen/date_i.dat",
     ".yardoc/objects/Henshin/Gen/extension_3D_i.dat",
     ".yardoc/objects/Henshin/Gen/extension_i.dat",
     ".yardoc/objects/Henshin/Gen/initialize_i.dat",
     ".yardoc/objects/Henshin/Gen/layout_3D_i.dat",
     ".yardoc/objects/Henshin/Gen/layout_i.dat",
     ".yardoc/objects/Henshin/Gen/override_i.dat",
     ".yardoc/objects/Henshin/Gen/path_3D_i.dat",
     ".yardoc/objects/Henshin/Gen/path_i.dat",
     ".yardoc/objects/Henshin/Gen/payload_i.dat",
     ".yardoc/objects/Henshin/Gen/process_i.dat",
     ".yardoc/objects/Henshin/Gen/read_yaml_i.dat",
     ".yardoc/objects/Henshin/Gen/render_i.dat",
     ".yardoc/objects/Henshin/Gen/site_3D_i.dat",
     ".yardoc/objects/Henshin/Gen/site_i.dat",
     ".yardoc/objects/Henshin/Gen/title_3D_i.dat",
     ".yardoc/objects/Henshin/Gen/title_i.dat",
     ".yardoc/objects/Henshin/Gen/write_i.dat",
     ".yardoc/objects/Henshin/HTMLGenerator.dat",
     ".yardoc/objects/Henshin/HTMLGenerator/generate_i.dat",
     ".yardoc/objects/Henshin/JSGenerator.dat",
     ".yardoc/objects/Henshin/JSGenerator/generate_i.dat",
     ".yardoc/objects/Henshin/LayoutParser.dat",
     ".yardoc/objects/Henshin/LayoutParser/generate_i.dat",
     ".yardoc/objects/Henshin/Post.dat",
     ".yardoc/objects/Henshin/Post/author_3D_i.dat",
     ".yardoc/objects/Henshin/Post/author_i.dat",
     ".yardoc/objects/Henshin/Post/category_3D_i.dat",
     ".yardoc/objects/Henshin/Post/category_i.dat",
     ".yardoc/objects/Henshin/Post/date_3D_i.dat",
     ".yardoc/objects/Henshin/Post/date_i.dat",
     ".yardoc/objects/Henshin/Post/initialize_i.dat",
     ".yardoc/objects/Henshin/Post/override_i.dat",
     ".yardoc/objects/Henshin/Post/payload_i.dat",
     ".yardoc/objects/Henshin/Post/permalink_i.dat",
     ".yardoc/objects/Henshin/Post/process_i.dat",
     ".yardoc/objects/Henshin/Post/read_name_i.dat",
     ".yardoc/objects/Henshin/Post/read_yaml_i.dat",
     ".yardoc/objects/Henshin/Post/tags_3D_i.dat",
     ".yardoc/objects/Henshin/Post/tags_i.dat",
     ".yardoc/objects/Henshin/Post/title_3D_i.dat",
     ".yardoc/objects/Henshin/Post/title_i.dat",
     ".yardoc/objects/Henshin/Post/write_i.dat",
     ".yardoc/objects/Henshin/Site.dat",
     ".yardoc/objects/Henshin/Site/archives_3D_i.dat",
     ".yardoc/objects/Henshin/Site/archives_i.dat",
     ".yardoc/objects/Henshin/Site/categories_3D_i.dat",
     ".yardoc/objects/Henshin/Site/categories_i.dat",
     ".yardoc/objects/Henshin/Site/config_3D_i.dat",
     ".yardoc/objects/Henshin/Site/config_i.dat",
     ".yardoc/objects/Henshin/Site/gens_3D_i.dat",
     ".yardoc/objects/Henshin/Site/gens_i.dat",
     ".yardoc/objects/Henshin/Site/initialize_i.dat",
     ".yardoc/objects/Henshin/Site/layouts_3D_i.dat",
     ".yardoc/objects/Henshin/Site/layouts_i.dat",
     ".yardoc/objects/Henshin/Site/payload_i.dat",
     ".yardoc/objects/Henshin/Site/plugins_3D_i.dat",
     ".yardoc/objects/Henshin/Site/plugins_i.dat",
     ".yardoc/objects/Henshin/Site/posts_3D_i.dat",
     ".yardoc/objects/Henshin/Site/posts_i.dat",
     ".yardoc/objects/Henshin/Site/process_i.dat",
     ".yardoc/objects/Henshin/Site/read_i.dat",
     ".yardoc/objects/Henshin/Site/read_layouts_i.dat",
     ".yardoc/objects/Henshin/Site/read_others_i.dat",
     ".yardoc/objects/Henshin/Site/read_posts_i.dat",
     ".yardoc/objects/Henshin/Site/render_i.dat",
     ".yardoc/objects/Henshin/Site/reset_i.dat",
     ".yardoc/objects/Henshin/Site/statics_3D_i.dat",
     ".yardoc/objects/Henshin/Site/statics_i.dat",
     ".yardoc/objects/Henshin/Site/tags_3D_i.dat",
     ".yardoc/objects/Henshin/Site/tags_i.dat",
     ".yardoc/objects/Henshin/Site/write_i.dat",
     ".yardoc/objects/Henshin/StandardPlugin.dat",
     ".yardoc/objects/Henshin/configure_c.dat",
     ".yardoc/objects/Henshin/extensions_c.dat",
     ".yardoc/objects/Henshin/load_plugins_c.dat",
     ".yardoc/objects/LiquidPlugin.dat",
     ".yardoc/objects/LiquidPlugin/extensions_3D_i.dat",
     ".yardoc/objects/LiquidPlugin/extensions_i.dat",
     ".yardoc/objects/LiquidPlugin/generate_i.dat",
     ".yardoc/objects/LiquidPlugin/initialize_i.dat",
     ".yardoc/objects/LiquidPlugin/read_i.dat",
     ".yardoc/objects/MarukuPlugin.dat",
     ".yardoc/objects/MarukuPlugin/extensions_3D_i.dat",
     ".yardoc/objects/MarukuPlugin/extensions_i.dat",
     ".yardoc/objects/MarukuPlugin/generate_i.dat",
     ".yardoc/objects/MarukuPlugin/initialize_i.dat",
     ".yardoc/objects/PygmentsPlugin.dat",
     ".yardoc/objects/PygmentsPlugin/extensions_3D_i.dat",
     ".yardoc/objects/PygmentsPlugin/extensions_i.dat",
     ".yardoc/objects/PygmentsPlugin/generate_i.dat",
     ".yardoc/objects/PygmentsPlugin/initialize_i.dat",
     ".yardoc/objects/SassPlugin.dat",
     ".yardoc/objects/SassPlugin/extensions_3D_i.dat",
     ".yardoc/objects/SassPlugin/extensions_i.dat",
     ".yardoc/objects/SassPlugin/generate_i.dat",
     ".yardoc/objects/SassPlugin/initialize_i.dat",
     ".yardoc/objects/String.dat",
     ".yardoc/objects/String/directory_i.dat",
     ".yardoc/objects/String/extension_i.dat",
     ".yardoc/objects/String/file_name_i.dat",
     ".yardoc/objects/String/slugify_i.dat",
     ".yardoc/objects/root.dat",
     ".yardoc/proxy_types",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/henshin",
     "doc/Hash.html",
     "doc/Henshin.html",
     "doc/Henshin/CSSGenerator.html",
     "doc/Henshin/Gen.html",
     "doc/Henshin/HTMLGenerator.html",
     "doc/Henshin/JSGenerator.html",
     "doc/Henshin/LayoutParser.html",
     "doc/Henshin/Post.html",
     "doc/Henshin/Site.html",
     "doc/Henshin/StandardPlugin.html",
     "doc/LiquidPlugin.html",
     "doc/MarukuPlugin.html",
     "doc/PygmentsPlugin.html",
     "doc/SassPlugin.html",
     "doc/String.html",
     "doc/_index.html",
     "doc/class_list.html",
     "doc/css/common.css",
     "doc/css/full_list.css",
     "doc/css/style.css",
     "doc/file.README.html",
     "doc/file_list.html",
     "doc/frames.html",
     "doc/index.html",
     "doc/js/app.js",
     "doc/js/full_list.js",
     "doc/js/jquery.js",
     "doc/method_list.html",
     "doc/top-level-namespace.html",
     "henshin.gemspec",
     "lib/henshin.rb",
     "lib/henshin/ext.rb",
     "lib/henshin/gen.rb",
     "lib/henshin/plugin.rb",
     "lib/henshin/plugins/liquid.rb",
     "lib/henshin/plugins/maruku.rb",
     "lib/henshin/plugins/pygments.rb",
     "lib/henshin/plugins/sass.rb",
     "lib/henshin/post.rb",
     "lib/henshin/site.rb",
     "test/helper.rb",
     "test/site/_site/2010/10/20-testing-stuff/index.html",
     "test/site/_site/2010/5/15-lorem-ipsum/index.html",
     "test/site/_site/index.html",
     "test/site/index.html",
     "test/site/layouts/main.html",
     "test/site/layouts/post.html",
     "test/site/options.yaml",
     "test/site/posts/Testing-Stuff.markdown",
     "test/site/posts/lorem-ipsum.markdown",
     "test/test_henshin.rb"
  ]
  s.homepage = %q{http://github.com/hawx/henshin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Henshin is a static site generator}
  s.test_files = [
    "test/helper.rb",
     "test/test_henshin.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

