title:  Examplé Blog
author: You
url:    http://example.com

description: So I grew up in this place, with wires. Lots of wires. And then
             computers, then suddenly we were all in this place. A soup. A soup
             of wires. They call it the internet. I call it life.

projects:
- title: henshin
  url: http://github.com/hawx/henshin
  desc: The static site generator that created this site.
