title: Test Site
description: This is a site to test this site generator!
time_zone: GMT
author: Joshua Hawxwell

layout: post
type: blog

exclude: ['includes', 'css/_reset.sass']
post_name: '{title-with-dashes}.{extension}'
permalink: '/{year}/{month}/{date}/{title}/index.html'
plugins: [maruku, sass, liquid, test, textile, highlight, erb]

sass: 
  style: :compact
  
liquid:
  include_dir: includes